- name: template custom php.ini files
  template:
    src: templates/etc/php/all_versions/custom-php.ini.j2
    dest: "/etc/php/{{ php_fpm_version }}/{{ php_fpm_custom_ini_list_item['path'] }}"
    owner: root
    group: root
    mode: 0644
  when: php_fpm_custom_ini_list_item['state'] | default('present') != 'absent'
  with_items: "{{ php_fpm_custom_inis }}"
  loop_control:
    loop_var: php_fpm_custom_ini
  notify: restart php-fpm

- name: remove custom php.ini files with state absent
  file:
    path: "/etc/php/{{ php_fpm_version }}/{{ php_fpm_custom_ini_list_item['path'] }}"
    state: absent
  when: php_fpm_custom_ini_list_item['state'] | default('present') == 'absent'
  with_items: "{{ php_fpm_custom_inis }}"
  loop_control:
    loop_var: php_fpm_custom_ini
  notify: restart php-fpm
