- name: install PHP-FPM
  apt:
    name: "php{{ php_fpm_version }}-fpm"
    state: present

- name: uninstall PHP packages listed in php_fpm_packages_absent
  apt:
    name: "{{ php_fpm_packages_absent }}"
    state: absent
    update_cache: False

- name: install PHP packages listed in php_fpm_packages
  apt:
    name: "{{ php_fpm_packages }}"
    state: present
    update_cache: False


- name: download composer if defined
  get_url:
    url: "https://getcomposer.org/download/{{ php_fpm_composer_version }}/composer.phar"
    dest: "/usr/local/bin/composer-{{ php_fpm_composer_version }}"
    checksum: "{{ php_fpm_composer_checksum | default(None) }}"
    force: True
    owner: root
    group: root
    mode: 0755
  when: php_fpm_composer_version is defined

- name: download default composer if defined
  get_url:
    url: "https://getcomposer.org/download/{{ php_fpm_composer_default_version }}/composer.phar"
    dest: "/usr/local/bin/composer-{{ php_fpm_composer_default_version }}"
    checksum: "{{ php_fpm_composer_checksum | default(None) }}"
    force: True
    owner: root
    group: root
    mode: 0755
  when: php_fpm_composer_default_version is defined

- name: symlink default composer version as default if default version is defined
  file:
    state: link
    src: "/usr/local/bin/composer-{{ php_fpm_composer_default_version }}"
    dest: /usr/local/bin/composer
    force: True
    owner: root
    group: root
    mode: 0755
  when: php_fpm_composer_default_version is defined
