- name: verify that the given php_fpm_version is implemented
  fail:
    msg: "{{ php_fpm_version }} is not supported!"
  when: php_fpm_version | float not in php_supported_versions

- name: include install.yml
  include_tasks: install.yml

- name: include configure.yml
  include_tasks: configure.yml
