- name: include distro configurator
  include_tasks: '{{ distro_configurator }}'
  with_first_found:
    - configure/{{ ansible_distribution }}.{{ ansible_lsb.codename }}.yml
    - configure/{{ ansible_distribution }}.yml
    - configure/default.yml
  loop_control:
    loop_var: distro_configurator
