---
- name: restart php-fpm
  service:
    name: php{{ php_fpm_version }}-fpm
    state: restarted

- name: restart systemd-tmpfiles-clean.timer
  service:
    name: restart systemd-tmpfiles-clean.timer
    state: restarted
