- name: Converge
  hosts: all
  become: True
  vars:

    php_fpm_version: 7.4

    # Setup custom php.ini style config files
    php_fpm_custom_inis:
      - name: 99-custom.ini
        # templates /etc/php/{{ php_fpm_version }}/{{ target }}/conf.d/{{ path }}
        targets:
          - fpm
          - cli
        state: present
        vars:
          MySQL:
            mysql.allow_local_infile: On
            mysql.connect_timeout: 240
          Date:
            date.timezone: Europe/Berlin
          PHP:
            default_socket_timeout: 240
            expose_php: Off
            upload_max_filesize: 128M
            max_input_time: 240
            max_execution_time: 240
            max_file_uploads: 20
            max_input_vars: 1000
            post_max_size: 128M

  roles:
    - role: role-php-fpm
      # the name will be used to abstract the username, group name, logfile name (TODO should also be syslog prefix), tmpdir path
      # Make sure it only contains underscores, no dots! Dashes are allowed.
      php_fpm_pool_name: www_example_com
      # The php-fpm www dir, such as /var/www, below which the php_fpm_pool_dir will be created as the users home directory
      # default: /var/www
      php_fpm_www_dir: /var/www
      # the home dir for the user will be {{ php_fpm_www_dir }}/{{ php_fpm_pool_name }} (which is combined in the variable
      # php_fpm_home_dir by default)
      # append a custom path for a different chdir - default: omitted
      php_fpm_pool_chdir: htdocs
      # User and group ID for new user - default 1000
      php_fpm_pool_uid: 1050
      # size of the tmpfs for the tmpdir (in MB) - if omitted, no tmpfs is mounted
      php_fpm_pool_tmpdir_tmpfs_size: 128
      # Where to place the tmpdir for this particular pool. The the parent directory of this directory
      # is managed by ansbile and set to www-data:www-data 0550 so that webservers (like nginx and apache2)
      # works correctly with multiple Linux users
      php_fpm_pool_tmpdir: "/var/www/tmp/{{ php_fpm_pool_name }}"
      # php-fpm worker mode settings - I recommend setting php_fpm_pm to static
      # if you host LOTS of wordpresses you can use dynamic. start_servers, min and max_spare_servers are ignored by
      # php-fpm if you set to static, with static only max_children is relevant.
      php_fpm_pool_pm: dynamic
      php_fpm_pool_max_children: 8
      php_fpm_pool_start_servers: 3
      php_fpm_pool_min_spare_servers: 1
      php_fpm_pool_max_spare_servers: 4
      # will download /usr/local/bin/composer-1.8.0 and symlink it to /usr/local/wwwbin/www_beispiel_de/composer
      php_fpm_composer_version: 1.10.8
      # If defined, will download that version too and symlink it to /usr/local/bin/composer
      # If not defined, will symlink php_fpm_composer_version to /usr/local/bin/composer
      # Useful if one server runs multiple vhosts
      php_fpm_composer_default_version: 1.10.0
      # define additional key = value variables that are templated into the pool config
      php_fpm_pool_additional_variables:
        php_value[hostname]: www.example.com
        ping.path: /ping
        ping.response: pong
        php_admin_value[memory_limit]: 256M
        php_value[error_reporting]: 1
        php_value[display_errors]: on

    - role: role-php-fpm
      php_fpm_pool_name: www_beispiel_de
      php_fpm_pool_chdir: htdocs
      php_fpm_pool_uid: 1051
      php_fpm_pool_tmpdir_tmpfs_size: 128
      php_fpm_pool_pm: static
      php_fpm_pool_max_children: 2
      php_fpm_pool_additional_variables:
        php_value[hostname]: www.beispiel.de
        php_admin_value[memory_limit]: 128M
        php_value[error_reporting]: 1
        php_value[display_errors]: on
        php_admin_value[use_only_cookies]: 1
        php_admin_value[use_trans_sid]: 0
        php_admin_value[cookie_lifetime]: 36000
        php_admin_value[gc_maxlifetime]: 43200
        php_admin_value[upload_max_filesize]: 50M
        php_admin_value[post_max_size]: 50M
        php_admin_value[max_input_time]: 300
        php_admin_value[max_execution_time]: 300

    - role: role-php-fpm
      php_fpm_pool_name: www_ejemplo_es
      # if user and group is not set, a user called php_fpm_pool_name will be created
      php_fpm_pool_user: www-data
      # Optionally set a password for the user (might be required for vsftpd)
      # Run this with the password_hash sha512 filter!
      php_fpm_pool_password: "{{ secret | password_hash('sha512') }}"
      php_fpm_pool_group: www-data
      php_fpm_www_dir: /srv/www
      php_fpm_pool_chdir: app/htdocs
      # if user and group are set to 'www-data', always use 33!
      php_fpm_pool_uid: 33
      php_fpm_pool_tmpdir_tmpfs_size: 128
      php_fpm_pool_pm: static
      php_fpm_pool_max_children: 2
      php_fpm_pool_additional_variables:
        php_value[hostname]: www.ejemplo.es
        php_admin_value[memory_limit]: 128M
        php_value[error_reporting]: 1
        php_value[display_errors]: on

    - role: role-php-fpm
      php_fpm_pool_name: www_esempio_it
      php_fpm_pool_chdir: htdocs
      php_fpm_pool_uid: 1052
      php_fpm_pool_tmpdir_tmpfs_size: 128
      php_fpm_pool_pm: static
      php_fpm_pool_max_children: 2
      php_fpm_pool_additional_variables:
        php_value[hostname]: www.esempio.it
        php_admin_value[memory_limit]: 128M
        php_value[error_reporting]: 1
        php_value[display_errors]: on
        php_admin_value[use_only_cookies]: 1
        php_admin_value[use_trans_sid]: 0
        php_admin_value[cookie_lifetime]: 36000
        php_admin_value[gc_maxlifetime]: 43200
        php_admin_value[upload_max_filesize]: 50M
        php_admin_value[post_max_size]: 50M
        php_admin_value[max_input_time]: 300
        php_admin_value[max_execution_time]: 300



  post_tasks:

    - name: create a php.info file for the tests
      copy:
        content: |
            <?php
            phpinfo();
            ?>
        dest: "/var/www/{{ php_fpm_info_project_name }}/htdocs/info.php"
        owner: "{{ php_fpm_info_project_name }}"
        group: "{{ php_fpm_info_project_name }}"
        mode: 0640
        force: True
      with_items:
        - www_example_com
        - www_beispiel_de
        - www_esempio_it
      loop_control:
        loop_var: php_fpm_info_project_name

    - name: create a php.info file for the tests for www.ejemplo.es (www-data user and group)
      copy:
        content: |
            <?php
            phpinfo();
            ?>
        dest: "/srv/www/www_ejemplo_es/app/htdocs/info.php"
        owner: www-data
        group: www-data
        mode: 0640
        force: True

    - name: install libfcgi0ldbl for testing the socket
      apt:
        name: libfcgi0ldbl
        update_cache: False
