---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: stretch
    box: bento/debian-9
provisioner:
  name: ansible
  connection_options:
    ansible_become: yes
  lint:
    name: ansible-lint
scenario:
  name: remove
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
