- name: create pool configuration directory
  file:
    path: /etc/php/fpm/pool.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: configure php-fpm pools
  template:
    src: etc/php//fpm/pool.d/pool.conf.j2
    dest: /etc/php/fpm/pool.d/{{ php_fpm_pool_item['name'] }}.conf
    owner: root
    group: root
    mode: 0644
  with_items: "{{ php_fpm_pools }}"
  loop_control:
    loop_var: php_fpm_pool_item
