- name: deploy php.ini
  template:
    src: {{ php_fpm_config_directory }}/fpm/php.ini
    dest: /{{ php_fpm_config_directory }}/fpm/php.ini
    mode: 0644
    owner: root
    group: root

- name: deploy php-fpm.conf
  template:
    src: {{ php_fpm_config_directory }}/fpm/php-fpm.conf.j2
    dest: /{{ php_fpm_config_directory }}/fpm/php-fpm.conf
    mode: 0644
    owner: root
    group: root

- name: configure php-fpm pools
  template:
    src: {{ php_fpm_config_directory }}/fpm/pool.d/pool.conf.j2
    dest: /{{ php_fpm_config_directory }}/fpm/pool.d/{{ php_fpm_pool_item['name'] }}.conf
    mode: 0644
    owner: root
    group: root
  with_items: "{{ php_fpm_pools }}"
  loop_control:
    loop_var: php_fpm_pool_item
